model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 2
  latent_dim: 128

exp_params:
  dataset: DIY
  train_data_path: 'data/images/train/'
  test_data_path: 'data/images/test/'
  img_size: 128
  batch_size: 4 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_nb_epochs: 15
  max_epochs: 5

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"
  manual_seed: 1265

