model_params:
  name: 'EfficientNet'
  num_classes: 11
  compound_coef: 1
  anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  anchors_ratios: '[(1.9, 2.0), (0.71, 0.5), (0.87, 0.5)]'
  
exp_params:
  dataset: seal
  train_data_path: 'data/seal_detect/image/'
  train_ann_path:  'data/seal_detect/anno/'
  batch_size: 36 # Better to have a square number
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  input_size: 640
  num_workers: 8
  obj_list: ['circle', 'ellipse', 'rectangle', 'rhombus', 'square', 'squareinv', 'triangle']

trainer_params:
  gpus: -1
  max_nb_epochs: 3
  max_epochs: 5000

logging_params:
  save_dir: "logs/"
  name: "EfficientNet"
  manual_seed: 1265
