model_params:
  name: 'EfficientNet'
  num_classes: 2
  compound_coef: 1
  anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
  obj_list: ['icon','character']


exp_params:
  dataset: icon
  train_data_path: 'data/predict_image/images/'
  train_ann_path:  'data/predict_image/labels/'
  batch_size: 4 # Better to have a square number
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  input_size: 512
  num_workers: 4

trainer_params:
  gpus: 0
  max_nb_epochs: 15
  max_epochs: 5

logging_params:
  save_dir: "logs/"
  name: "EfficientNet"
  manual_seed: 1265
